export const companyExpenditures = [
  { category: " ", items: [" "] },
  { category: "Operating Expenses", items: ["Rent", "Utilities", "Office supplies", "Insurance", "Technology subscriptions"] },
  { category: "Employee Costs", items: ["Benefits (healthcare, retirement)", "Bonuses", "Training and development"] },
  { category: "Vendor Payments", items: ["Supplier payments", "Contractor fees", "Service provider fees"] },
  { category: "Marketing and Advertising", items: ["Campaign costs", "Promotions", "Digital ads (social media, search engines)", "Sponsorships"] },
  { category: "Capital Expenditures", items: ["Equipment purchases", "Office furniture", "Software and licenses", "Machinery"] },
  { category: "Debt Repayments", items: ["Loan repayments", "Interest payments", "Credit line payments"] },
  { category: "Taxes and Compliance", items: ["Income taxes", "Regulatory fees", "Industry-specific licenses", "Legal and audit fees"] },
  { category: "R&D and Innovation", items: ["Research and development expenses", "Product development costs", "Prototype creation"] },
  { category: "Travel and Entertainment", items: ["Business travel expenses", "Client meetings", "Company events and team-building activities"] },
  { category: "Departmental Spending", items: ["Department-specific supplies", "Equipment and resources", "Software licenses for departmental use", "Training or team-building activities for departments"] },
  { category: "Partnership Costs", items: ["Joint venture payments", "Revenue-sharing agreements", "Partner incentives", "Collaborative project costs"] },
  { category: "Miscellaneous Expenses", items: ["Donations and charity contributions", "Membership fees (professional organizations)", "Miscellaneous overhead"] },
];